# Generated by Django 5.2.9 on 2026-01-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_type', models.CharField(default='qris', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settlement', 'Paid'), ('expire', 'Expired'), ('deny', 'Denied'), ('cancel', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('qr_url', models.URLField(blank=True)),
                ('qr_string', models.TextField(blank=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('midtrans_response', models.JSONField(blank=True, default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
